name: springboot_security_open_template

volumes:
  postgres-data:
  gradle-cache: # Only keep Gradle cache

services:
  app:
    container_name: javadev
    build:
      context: .
      dockerfile: Dockerfile
      args:
        JAVA_VERSION: "${JAVA_VERSION:-21}"
        GRADLE_VERSION: "${GRADLE_VERSION:-8.5}"
    env_file:
      - ../.env
    environment:
      POSTGRES_HOSTNAME: db
    volumes:
      - ../..:/workspaces:cached
      - gradle-cache:/home/vscode/.gradle # Only keep Gradle volume mount
    command: sleep infinity
    networks:
      - spring-net

  db:
    container_name: postgresdb
    image: postgres:17.2-bullseye
    restart: unless-stopped
    env_file:
      - ../.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - spring-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-spacecodee}"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  spring-net:
    driver: bridge
