package com.spacecodee.springbootsecurityopentemplate.enums;

public enum RolePermissionEnum {

    // System
    CREATE_ONE_SYSTEM_ADMIN,
    UPDATE_ONE_SYSTEM_ADMIN,
    UPDATE_STATUS_ONE_SYSTEM_ADMIN,
    DELETE_ONE_SYSTEM_ADMIN,
    FIND_ONE_SYSTEM_ADMIN,
    FIND_ONE_DETAIL_SYSTEM_ADMIN,
    FIND_ALL_PAGE_SYSTEM_ADMINS,

    // Developer
    CREATE_ONE_DEVELOPER,
    DELETE_ONE_DEVELOPER,
    UPDATE_ONE_DEVELOPER,
    UPDATE_STATUS_ONE_DEVELOPER,
    FIND_ONE_DEVELOPER,
    FIND_ONE_DETAIL_DEVELOPER,
    FIND_ALL_PAGE_DEVELOPERS,

    // Manager
    CREATE_ONE_MANAGER,
    DELETE_ONE_MANAGER,
    UPDATE_ONE_MANAGER,
    UPDATE_STATUS_ONE_MANAGER,
    FIND_ONE_MANAGER,
    FIND_ONE_DETAIL_MANAGER,
    FIND_ALL_PAGE_MANAGERS,

    // Editor
    CREATE_ONE_EDITOR,
    DELETE_ONE_EDITOR,
    UPDATE_ONE_EDITOR,
    UPDATE_STATUS_ONE_EDITOR,
    FIND_ONE_EDITOR,
    FIND_ONE_DETAIL_EDITOR,
    FIND_ALL_PAGE_EDITORS,

    // Viewer
    CREATE_ONE_VIEWER,
    DELETE_ONE_VIEWER,
    UPDATE_ONE_VIEWER,
    UPDATE_STATUS_ONE_VIEWER,
    FIND_ONE_VIEWER,
    FIND_ONE_DETAIL_VIEWER,
    FIND_ALL_PAGE_VIEWER,

    // Guest
    CREATE_ONE_GUEST,
    DELETE_ONE_GUEST,
    UPDATE_ONE_GUEST,
    UPDATE_STATUS_ONE_GUEST,
    FIND_ONE_GUEST,
    FIND_ONE_DETAIL_GUEST,
    FIND_ALL_PAGE_GUEST,

    // User
    SHOW_USER_PROFILE,

    // System
    VALIDATE_TOKEN,
    LOGOUT,
    REFRESH_TOKEN,

    // Module
    CREATE_ONE_MODULE,
    UPDATE_ONE_MODULE,
    DELETE_ONE_MODULE,
    FIND_ONE_MODULE,
    FIND_ALL_MODULE,
    FIND_ALL_PAGE_MODULE,

    // Operation
    CREATE_ONE_OPERATION,
    UPDATE_ONE_OPERATION,
    DELETE_ONE_OPERATION,
    FIND_ONE_OPERATION,
    FIND_ONE_DETAIL_OPERATION,
    FIND_ALL_PAGE_OPERATION,
    FIND_ALL_OPERATION_BY_MODULE,
    FIND_ALL_OPERATION,

    // Role
    CREATE_ONE_ROLE,
    UPDATE_ONE_ROLE,
    DELETE_ONE_ROLE,
    FIND_ONE_ROLE,
    FIND_ONE_DETAIL_ROLE,
    FIND_ALL_PAGE_ROLE,
    FIND_ALL_ROLE,

    // Permission
    CREATE_ONE_PERMISSION,
    UPDATE_ONE_PERMISSION,
    DELETE_ONE_PERMISSION,
    FIND_ONE_PERMISSION,
    FIND_ONE_DETAIL_PERMISSION,
    FIND_ALL_PAGE_PERMISSION,
    FIND_ALL_PERMISSION,
    FIND_ALL_PERMISSION_BY_ROLE,

    // Permission JWT
    FIND_PERMISSIONS_BY_CURRENT_USER,

    // Cache Monitoring
    GET_CACHE_STATS,

    // Rate Limit Monitoring
    GET_RATE_LIMIT_STATS,
    RESET_IP_RATE_LIMIT,
    CLEAN_UP_RATE_LIMIT
}
